### PR TITLE
Update MRAs for IREM 52 & 72

### PR DESCRIPTION
**Pull request by tdelage26**

### CODE REVIEW

**Comment by gyurco** [comment]
Thanks!
Two notices:
1. _Please rebase your local copy_ before issuing more PRs.
2. Does it actually work for you? Many cores has joystick_0 and _1 defined in 8 bits only ([7:0]), no way that .START1(10) and such work. Solution: change joystick_0 and _1 to 32 bits, that's future proof (wire  [31:0] joystick_0;).

**Comment by tdelage26** [comment]
Yes everything works for me (i'm testing all games one by one). Anyway i'll change joystick_0 and joystick_1 to 32 bits just for safety.

**Comment by tdelage26** [comment]
Ok i resynched my local copy and i'm told "this branch is not behind the upstream" which should be good. I updated the joysticks to 32 bits and added the mods to PR.

**Comment by gyurco** [comment]
As the 'resync' was a merge, not rebase, your repo now is quite a mess. I suggest to delete and re-fork it. I cherry-picked the relevant changes, so they won't be lost.

**Pull request closed without merging**
