### PR TITLE
Update Hammerin' Harry (US, M84 hardware).mra

### PR DESCRIPTION
**Pull request by alessioscand**
Fixed ZIP namefile

### CODE REVIEW

**Comment by gyurco** [comment]
What about merged roms?

**Comment by alessioscand** [comment]
`hharryu.zip|hharry.zip` would be better? (as in Daiku no Gensan)

**Comment by gyurco** [comment]
Probably yes.

**Comment by alessioscand** [comment]
Fixed, thank you.

**Pull request merged**
